### PR TITLE
Notification scheduling and displaying

### PR DESCRIPTION
**Pull request by Chriskkirilov**
This pull request introduces a Notification Service to the To-Do List application, enhancing user experience by providing timely alerts for upcoming tasks. The service utilizes the browser's Notification API to notify users about tasks approaching their due dates, ensuring they stay on track with their responsibilities.

**Features**

- Task Notifications: Users receive notifications for tasks that are due soon, configurable based on user preferences for how much notice they want (e.g., 1 hour before due date).
- User Preferences: The notification timing can be adjusted by users, allowing them to set their preferred reminder offset.
- Notification Scheduling: Notifications are dynamically scheduled based on the due dates of tasks, ensuring timely alerts without overwhelming the user.
- Notification History: The service maintains a history of displayed notifications, providing insights into past alerts and allowing for better task management.
Integration with Local Storage: Tasks and user preferences are stored in local storage, ensuring data persistence across sessions.

### CODE REVIEW

**Review by GalyaPandeva — CHANGES_REQUESTED** [review]
I suggest improving the NotificationService by ensuring that task.dueDate is consistently parsed as a Date object and enhancing permission handling for notifications to include error management for denied permissions. It would also be beneficial to allow the notification icon path to be configurable, adjust the notification checking interval via user preferences, and implement memory management to limit notification history growth. Lastly, adding error handling for local storage operations and including unit tests for key methods will further strengthen the service.

**Comment by Chriskkirilov** [comment]
Hey, @GalyaPandeva , just a reminder to review the changes regarding the notifications suggestions.

**Review by GalyaPandeva — APPROVED** [review]
Everything looks good now, thank you.

**Comment by Chriskkirilov** [comment]
Ready for merge :)

**Pull request merged**
